# Generated by Django 3.1.4 on 2021-03-02 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0007_auto_20210302_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='Value of Order Unit')),
                ('status', models.CharField(choices=[('wait', 'Wait'), ('cnl', 'Cancel'), ('dlvrd', 'Delivered')], max_length=25, verbose_name='Status')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Order Unit',
                'verbose_name_plural': 'Order Units',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('crt', 'Created'), ('wrk', 'In work'), ('cls', 'Closed'), ('paid', 'Paid')], max_length=25, verbose_name='Status')),
                ('products', models.ManyToManyField(default=None, to='orders.OrderUnit', verbose_name='Products')),
            ],
            options={
                'verbose_name': 'Порядок',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
