# Generated by Django 3.1.4 on 2021-03-02 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210301_1259'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuposition',
            options={'verbose_name': 'Position', 'verbose_name_plural': 'Position'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Order'},
        ),
        migrations.AlterField(
            model_name='menuposition',
            name='dish',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.dish'),
        ),
        migrations.AlterField(
            model_name='menuposition',
            name='drink',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.drink'),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(default=None, to='orders.MenuPosition'),
        ),
    ]
