# Generated by Django 3.1.4 on 2021-02-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
        migrations.AlterModelOptions(
            name='dishcategory',
            options={'verbose_name': 'Категория блюда', 'verbose_name_plural': 'Категории блюда'},
        ),
        migrations.AlterModelOptions(
            name='drink',
            options={'verbose_name': 'Напиток', 'verbose_name_plural': 'Напитки'},
        ),
        migrations.AlterModelOptions(
            name='drinkcategory',
            options={'verbose_name': 'Категория напитка', 'verbose_name_plural': 'Категории напитка'},
        ),
        migrations.RemoveField(
            model_name='dish',
            name='alcohol',
        ),
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ImageField(default=None, upload_to='', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drink',
            name='alcohol',
            field=models.BooleanField(default=False, verbose_name='Алкогольный'),
        ),
        migrations.AddField(
            model_name='drink',
            name='image',
            field=models.ImageField(default=None, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=55, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='volume',
            field=models.IntegerField(verbose_name='Объем'),
        ),
        migrations.AlterField(
            model_name='dishcategory',
            name='name',
            field=models.CharField(max_length=55, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='name',
            field=models.CharField(max_length=55, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='drinkcategory',
            name='name',
            field=models.CharField(max_length=55, unique=True, verbose_name='Наименование'),
        ),
    ]
