# Generated by Django 3.1.4 on 2021-02-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210227_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='weight',
        ),
        migrations.AddField(
            model_name='dish',
            name='measurement',
            field=models.CharField(choices=[('KG', 'killogramm'), ('GR', 'gramm'), ('ML', 'mill'), ('L', 'liter')], default='killogramm', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drink',
            name='measurement',
            field=models.CharField(choices=[('KG', 'killogramm'), ('GR', 'gramm'), ('ML', 'mill'), ('L', 'liter')], default='killogramm', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drink',
            name='volume',
            field=models.IntegerField(default='0', verbose_name='Объем'),
            preserve_default=False,
        ),
    ]
