# Generated by Django 3.1.4 on 2021-03-02 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210302_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='alcohol',
        ),
    ]
